### ISSUE TITLE
struct works where pointers do not, to read 32-bit float on 8-bit CPU

### ISSUE THREAD

**Issue by jbeale1** [pranjal-joshi/TSD305Lib-Arduino#2]
On line 70 of tsd305lib.cpp, the code for tsdReadFloat() uses pointers to convert two 16-bit words to a 32-bit float. This compiles without error, but did not work on my board. It was always giving me 0.00 on an Arduino-UNO compatible board (based on ATmega328p 8-bit CPU).  The code below implementing this function using a struct, based on the example in the TE Connectivity datasheet for TSD305 DIGITAL TEMPERATURE SENSORS, does work OK for me.

// Get float value from TSD EEPROM
float tsd305::tsdReadFloat(uint8_t addr) {
  union i16f32  {
    unsigned int iValue[2]; // 16bit unsigned integer
    float fValue;           // float IEEE 754
  } w32;

  w32.iValue[1] = tsdReadCoef(addr);
  w32.iValue[0] = tsdReadCoef(addr+1);
  return w32.fValue;
}

**Comment by pranjal-joshi** [comment]
@jbeale1 

https://github.com/pranjal-joshi/TSD305Lib-Arduino/blob/6b21a2896e72cf7a7f2b81bf745eb6d930f9559b/tsd305lib.cpp#L76

Casting to float may lead to undefined behavior or incorrect results due to endianness differences or other platform-specific considerations. If you're sure about the memory layout of the uint32_t value and how it represents a float, and you're certain about the byte order (endianness) of your platform, you can proceed with this approach.

**Comment by jbeale1** [comment]
I'm confused. Casting to float is the way the code in the library is currently implemented, but as you point out, it's risky. It doesn't work on Arduino Uno, perhaps the most common Arduino. It does work OK on Arduino Uno using the struct as I suggested, which is also suggested by TE Connectivity, the manufacturer of the part. So is there a reason to prefer the risky way?

**Comment by pranjal-joshi** [comment]
Because my target platform was ESP8266 while creating this library and it worked.
Note thay ESP and AVR have different C compilers
